In [2]:
import numpy as np

## numpy array 

In [5]:
benimListem = [20,30,40]
type(benimListem)

list

In [11]:
np.array(benimListem)

array([20, 30, 40])

In [13]:
type(np.array(benimListem))

numpy.ndarray

In [15]:
matrixList = [[10,20,30],[20,30,40],[30,40,50]]
matrixList[1][0]

20

In [17]:
np.array(matrixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## arange

In [20]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## zeros and ones

In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [37]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [39]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [41]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## linspaces

In [45]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [47]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [49]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [51]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## eye

In [54]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random

In [58]:
np.random.randn(8)

array([ 0.77149412,  0.12802692,  0.0306046 , -0.44133719,  0.82430185,
       -0.05664686, -0.52297767,  1.99369326])

In [60]:
np.random.randn(4,4)

array([[ 1.22880642,  0.55126136,  0.3431563 ,  1.1053139 ],
       [-0.36936449,  0.99029922, -1.11007276,  0.63983121],
       [ 2.17032368, -0.40415877, -2.44386271, -0.8663784 ],
       [ 0.54932172, -1.30704715,  0.18629506, -0.8212791 ]])

In [62]:
np.random.randint(1,10)

4

In [64]:
np.random.randint(1,10)

8

In [68]:
np.random.randint(1,300,5)

array([  2, 166,  98, 153,  73])

In [70]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [74]:
benimRandomDizim = np.random.randint(0,100,30)
benimRandomDizim

array([59, 35, 97, 50, 12, 76,  7, 98, 67, 15, 93, 81, 58, 98, 21, 46, 79,
        8,  1, 48, 90, 21, 15, 57, 13, 78, 91, 65, 73, 33])

## numpy dizi metodları

In [78]:
benimNumpyDizim.reshape(5,6) 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [80]:
benimNumpyDizim.max() 

29

In [82]:
benimNumpyDizim.min() 

0

In [84]:
benimRandomDizim.max()

98

In [86]:
benimRandomDizim.argmax()

7

In [88]:
benimRandomDizim.argmin()

18

In [92]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [94]:
reshapeDizim

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [96]:
benimDizim = np.arange(0,15)

In [98]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [100]:
benimDizim[5]

5

In [104]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [106]:
benimDizim[3:8] = -5
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [110]:
baskaDizi = np.arange(0,25)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [120]:
slicingDizisi = baskaDizi[4:9]
slicingDizisi

array([4, 5, 6, 7, 8])

In [122]:
type(slicingDizisi)

numpy.ndarray

In [126]:
slicingDizisi[:] = 700
slicingDizisi

array([700, 700, 700, 700, 700])

In [128]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [130]:
ornekDizi = np.arange(0,24)
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [132]:
ornekDiziKopyasi = ornekDizi.copy()
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [134]:
ornekDiziKopyaSlicing = ornekDiziKopyasi[3:6]

In [136]:
ornekDiziKopyaSlicing[:] = 800

In [138]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [140]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## Matrix

In [143]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [145]:
benimMatrixDizim = np.array(benimListem)
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [147]:
benimMatrixDizim[0]

array([10, 20, 30])

In [149]:
benimMatrixDizim[1][2]

40

In [151]:
benimMatrixDizim[1,2]

40

In [155]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [157]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [159]:
yeniMatrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

## Operations

In [164]:
yeniBirDizi = np.random.randint(1,100,20)
yeniBirDizi

array([80, 71, 36, 83, 86,  1, 26, 30, 55, 28,  8, 40, 44, 91, 43, 38, 64,
       56, 67, 76])

In [166]:
yeniBirDizi > 24

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [168]:
yeniBirDizi

array([80, 71, 36, 83, 86,  1, 26, 30, 55, 28,  8, 40, 44, 91, 43, 38, 64,
       56, 67, 76])

In [178]:
sonucDizisi = yeniBirDizi > 24
sonucDizisi

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [180]:
yeniBirDizi

array([80, 71, 36, 83, 86,  1, 26, 30, 55, 28,  8, 40, 44, 91, 43, 38, 64,
       56, 67, 76])

In [182]:
yeniBirDizi[sonucDizisi]

array([80, 71, 36, 83, 86, 26, 30, 55, 28, 40, 44, 91, 43, 38, 64, 56, 67,
       76])

In [184]:
yeniBirDizi

array([80, 71, 36, 83, 86,  1, 26, 30, 55, 28,  8, 40, 44, 91, 43, 38, 64,
       56, 67, 76])

In [186]:
yeniBirDizi[yeniBirDizi > 24]

array([80, 71, 36, 83, 86, 26, 30, 55, 28, 40, 44, 91, 43, 38, 64, 56, 67,
       76])

In [188]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [190]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [192]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [194]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [196]:
sonDizi / sonDizi

C:\Users\birca\AppData\Local\Temp\ipykernel_19228\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [198]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [200]:
np.max(sonDizi)

23

In [202]:
np.min(sonDizi)

0